xcodebuild_arguments: [clean,build,-workspace,Tempura.xcworkspace,-scheme,Tempura]
author: Bending Spoons Team
author_url: http://bendingspoons.com
github_url: https://github.com/BendingSpoons/tempura-lib-swift
github_file_prefix: https://github.com/BendingSpoons/tempura-lib-swift/blob/master/
copyright: 2017 [Bending Spoons](https://bendingspoons.com)
output: docs/latest